version: '3.8'
services:
  php-imdb-api:
    build:
      context: ./php-imdb-api
    environment:
      - PHP_ERROR_REPORTING=E_ALL & ~E_DEPRECATED
    ports:
      - "8001:80"
      - "9004:9004"
    networks:
      - app-network
    volumes:
      - ./cache:/var/www/html/src/cache

  demo-app:
    build:
      context: ./demo
    container_name: demo-app
    ports:
      - "8080:8080"
      - "5005:5005" # Debugging port
    networks:
      - app-network
    depends_on:
      - php-imdb-api

  php-ui:
    build:
      context: ./php-ui-app
    container_name: php-ui
    ports:
      - "8000:80"
    depends_on:
      - demo-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
